- name: "Type: Bug"
  color: "e80c0c"
  description: Something isn't working as expected.
  from_name: "Bug"

- name: "Design"
  color: "FFA07A"
  description: Something isn't working as expected.

- name: "Database"
  color: "FBCA04"
  description: Issues related to the database or data storage.

- name: "Good for NewComers"
  color: "40E0D0"
  description: Issues suitable for new contributors who want to get involved in the project.

- name: "Help wanted"
  color: "35b6c0"
  description: Issues that need help or assistance from the community to be resolved.

- name: "Need details"
  color: "FF69B4"
  description: Issues that require more information or details to be properly addressed.

- name: "POC"
  color: "0E8A16"
  description: Issues related to creating or testing a proof of concept for a new feature or idea.

- name: "Release"
  color: "32CD32"
  description: Issues related to preparing or managing a software release.

- name: "Research"
  color: "C2E0C6"
  description: Issues related to research or investigation of a problem or potential feature.

- name: "Tech Debt"
  color: "FBCA04"
  description: Issues related to technical debt, such as refactoring or cleaning up code.

- name: "Discord"
  color: "5319E7"
  description: Issues related to the project's Discord community or communication channels.

- name: "Type: Enhancement"
  color: "54b2ff"
  description: Suggest an improvement for an existing feature.
  from_name: "Enhancement"

- name: "Type: Feature"
  color: "54b2ff"
  description: Suggest a new feature.

- name: "Type: Security"
  color: "fbff00"
  description: A problem or enhancement related to a security issue.

- name: "Type: Question"
  color: "9309ab"
  description: Request for information.
  from_name: "Question"

- name: "Type: Test"
  color: "ce54e3"
  description: A problem or enhancement related to a test.

- name: "Duplicate"
  color: "EB862D"
  description: Duplicate of another issue.

- name: "Invalid"
  color: "faef50"
  description: This issue doesn't seem right.

- name: "Documentation"
  color: "2fbceb"
  description: An issue/change with the documentation.

- name: "Won't fix"
  color: "C8D9E6"
  description: Reported issue is working as intended.

- name: "3rd party issue"
  color: "e88707"
  description: This issue might be caused by a 3rd party script/package/other reasons

- name: "OS: Windows"
  color: "AEB1C2"
  description: Is Windows-specific

- name: "OS: Mac"
  color: "AEB1C2"
  description: Is Mac-specific

- name: "OS: Linux"
  color: "AEB1C2"
  description: Is Linux-specific
